### PR TITLE
add python download scripts

### LINKED ISSUE #3: Provide an estimated dl size
The bash scripts beg the question: about how big is the entire archive?

### LINKED ISSUE #6: Rewrite/refactor download scripts
A download script that would grab IDs from the csv and use it to get the raw xml would be more flexible to changes and easier to document and understand.

I'll take a stab at this.

### PR DESCRIPTION
**Pull request by pierwill**
The two scripts gets IDs from the csv file and download the available records automatically.

Also document script usage and estimated download size.

fixes #3 and fixes #6

### CODE REVIEW

**Comment by pierwill** [comment]
What is the archive's size? 16GB was an estimate. Currently downloading the archive, will report back.

**Comment by pierwill** [comment]
Update the README with all three project names and an accurate dl size.

**Comment by pierwill** [comment]
@jamescummings Hello! Just wondering if this repo is still maintained or if any maintainers are available to look at this.

**Comment by pierwill** [comment]
👋

**Comment by rajaaaaa** [comment]
🙋

**Pull request closed without merging**
